[package]
name = "cogumeta-studios/cursor"
version = "1.0.0"
exclude = [ "**" ]
include = [
  "src/**/*",
  "lib/**/*",
  "default.project.json",
  "vaulty.toml"
]

[dev-dependencies]
Specium = "thecogumeta/rbx-specium@*"
